(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
BeginPackage["biasreduction`"]


reducebiases::usage="Get minimum number of biases";


Begin["`Private`"]


reducebiases[Aranges0_,Branges0_]:=Module[{Aranges=Aranges0,Branges=Branges0},
biases={};

(*indices represent: [[(list index),AorB,Di,Mi]]*)
(*maybe not AorB since I might sum them at the end*)
UVdivs={};
IRdivs={};

{biases,IRdivs,UVdivs}
]



End[] (*End Private Context*)

EndPackage[]



