(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)

BeginPackage["fftlog`"]


q0kmqmuqdecomp::usage="decompose expression into sum of powers of q0, kmq and muq ";
n1::usage="fftlog index from first power spectrum";
n2::usage="fftlog index from second power spectrum";

Begin["`Private`"]
Get[NotebookDirectory[]<>"globalvars.m"] ;
Get[NotebookDirectory[]<>"losintegrals.m"];
Get[NotebookDirectory[]<>"losintcalcs.m"];



q0kmqmuqdecomp[v0_]:=Module[{v=v0},
v=Expand[v];
Tv=Table[{ q0 D[v[[l]],q0]/v[[l]],kmq D[v[[l]],kmq]/v[[l]],muq D[v[[l]],muq]/v[[l]],v[[l]]/. {q0->1,kmq->1,muq->1}},{l,1,Length[v]}];
Coefs={};
Tuniq={};
For[i=1,i<Length[Tv]+1,i++,
If[!MemberQ[Coefs,Tv[[i,{1,2,3}]]],AppendTo[Coefs,Tv[[i,{1,2,3}]]];AppendTo[Tuniq,Tv[[i]]],coefind=Position[Coefs,Tv[[i,{1,2,3}]]][[1]];Tuniq[[coefind,4]]+=Tv[[i,4]];]
];
(*S=Sum[v1[[m,4]] J2[1,v1[[m,1]]+n1,v1[[m,2]]+n2]/J2[1,n1,n2],{m,1,Length[v1]}]*)
Sum[ Tuniq[[m,4]] losint[-(Tuniq[[m,1]]-Tuniq[[m,3]])/2+n1, -Tuniq[[m,2]]/2+n2,Tuniq[[m,3]]],{m,1,Length[Tuniq]}]
]

End[] (*End Private Context*)

EndPackage[]



