(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)

BeginPackage["losintegrals`"]
J2::usage="J2 fct";
I2::usage="I2 fct";

A1::usage :=" A1 Kernel";
A2::usage :=" A2 Kernel";
A3::usage :=" A3 Kernel";
A4::usage :=" A4 Kernel";
A5::usage :=" A5 Kernel";
A6::usage :=" A6 Kernel";
A7::usage :=" A7 Kernel";
A8::usage :=" A8 Kernel";
A9::usage :=" A9 Kernel";
A10::usage :=" A10 Kernel";
A11::usage :=" A11 Kernel";
A12::usage :=" A12 Kernel";

B1::usage :=" B1 Kernel";
B2::usage :=" B2 Kernel";
B3::usage :=" B3 Kernel";
B4::usage :=" B4 Kernel";
B5::usage :=" B5 Kernel";
B6::usage :=" B6 Kernel";
B7::usage :=" B7 Kernel";
B8::usage :=" B8 Kernel";
B9::usage :=" B9 Kernel";
B10::usage :=" B10 Kernel";
B11::usage :=" B11 Kernel";
B12::usage :=" B12 Kernel";


C4::usage :=" C4 Kernel";
C5::usage :=" C5 Kernel";
C6::usage :=" C6 Kernel";
C7::usage :=" C7 Kernel";
C8::usage :=" C8 Kernel";
C9::usage :=" C9 Kernel";
C10::usage :=" C10 Kernel";
C11::usage :=" C11 Kernel";
C12::usage :=" C12 Kernel";


D6::usage :=" D6 Kernel";
D7::usage :=" D7 Kernel";
D8::usage :=" D8 Kernel";
D9::usage :=" D9 Kernel";
D10::usage :=" D10 Kernel";
D11::usage :=" D11 Kernel";
D12::usage :=" D12 Kernel";

E8::usage :=" E8 Kernel";
E9::usage :=" E9 Kernel";
E10::usage :=" E10 Kernel";
E11::usage :=" E11 Kernel";
E12::usage :=" E12 Kernel";

F10::usage :=" F10 Kernel";
F11::usage :=" F11 Kernel";
F12::usage :=" F12 Kernel";

G12::usage :=" G12 Kernel";
Begin["`Private`"]
Get[NotebookDirectory[]<>"globalvars.m"] ;


(*integrals of easy to calculate gamma functions that result from master (https://arxiv.org/pdf/1708.08130) and line of sight(https://arxiv.org/pdf/2402.09778) integrals *)
J2[\[Nu]1_,\[Nu]2_]:=1/(2\[Pi])^3 (Gamma[3/2-\[Nu]1]Gamma[3/2-\[Nu]2]Gamma[\[Nu]1+\[Nu]2-3/2])/(Gamma[\[Nu]1]Gamma[\[Nu]2]Gamma[3-\[Nu]1-\[Nu]2]) \[Pi]^(3/2) k0^(3-2\[Nu]1-2\[Nu]2);

I2[\[Nu]1_,\[Nu]2_]:=1/(2\[Pi])^3 (Gamma[3/2-\[Nu]1]Gamma[3/2-\[Nu]2]Gamma[\[Nu]1+\[Nu]2-3/2])/(Gamma[\[Nu]1]Gamma[\[Nu]2]Gamma[3-\[Nu]1-\[Nu]2]) \[Pi]^(3/2);


(* Its possible to insert here the expressions of the line of sight functions A1,...G12 in order to only have Gamma functions at the end however this can result in very long final expressions and the overhead from calling the functions shouldn't be too large*)

End[] 
 
EndPackage[]



