(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)

BeginPackage["quadfcts`"]

F2::usage="F2 Kernel";
G2::usage="G2 Kernel";
S2::usage="G2 Kernel";
Dlist::usage="Array of D Kernels";

D1::usage="D1 Kernel";
D2::usage="D2 Kernel";
D3::usage="D3 Kernel";
D4::usage="D4 Kernel";
D5::usage="D5 Kernel";
D6::usage="D6 Kernel";
D7::usage="D7 Kernel";
D8::usage="D8 Kernel";
D9::usage="D9 Kernel";
D10::usage="D10 Kernel";
D11::usage="D11 Kernel";
D12::usage="D12 Kernel";
D13::usage="D13 Kernel";
D14::usage="D14 Kernel";


Begin["`Private`"]
Get[NotebookDirectory[]<>"globalvars.m"] ;
(*Get[NotebookDirectory[]<>"util.m"] ;*)
F2[v1_,v2_]:=5/7+0.5 Dot[v1,v2] (1/Norm[v1]^2+1/Norm[v2]^2)+(2/7) (Dot[v1,v2]/(Norm[v1] Norm[v2]))^2;

G2[v1_,v2_]:=3/7+0.5 Dot[v1,v2] (1/Norm[v1]^2+1/Norm[v2]^2)+(4/7) (Dot[v1,v2]/(Norm[v1] Norm[v2]))^2;


S2[v1_,v2_]:=(Dot[v1,v2]/Norm[v1] Norm[v2])^2-1;

D1[v1_,v2_]:=F2[v1,v2];

D2[v1_,v2_]:=1;

D3[v1_,v2_]:=S2[v1,v2];

D4[v1_,v2_]:=(-v1[[3]]-v2[[3]]) (v1[[3]]/Norm[v1]^2+v2[[3]]/Norm[v2]^2);

D5[v1_,v2_]:=(F2[v1,v2] ((v1[[3]]/Norm[v1])^2+(v2[[3]]/Norm[v2]^2))+(-v1[[3]]-v2[[3]])^2/(Sqrt[(-v1[[1]]-v2[[1]])^2+(-v1[[2]]-v2[[2]])^2+(-v1[[3]]-v2[[3]])^2]^2) G2[v1,v2]);

D6[v1_,v2_]:=((v1[[3]]/Norm[v1])^2+(v2[[3]]/Norm[v2]^2));

D7[v1_,v2_]:=S2[v1,v2] ((v1[[3]]/Norm[v1])^2+(v2[[3]]/Norm[v2]^2));

D8[v1_,v2_]:=(-v1[[3]]-v2[[3]]) (v1[[3]]^3/Norm[v1]^4+v2[[3]]^3/Norm[v2]^4+2 v1[[3]] (v2[[3]]/(Norm[v1] Norm[v2]))^2+2 v2[[3]] (v1[[3]]/(Norm[v1] Norm[v2]))^2);

D9[v1_,v2_]:=((v1[[3]] v2[[3]]/(Norm[v1] Norm[v2]))^2 F2[v1,v2]+((v1[[3]]/Norm[v1])^2+(v2[[3]]/Norm[v2])^2) ((-v1[[3]]-v2[[3]])/(Sqrt[(-v1[[1]]-v2[[1]])^2+(-v1[[2]]-v2[[2]])^2+(-v1[[3]]-v2[[3]])^2]))^2 G2[v1,v2]);

D10[v1_,v2_]:=(v1[[3]] v2[[3]]/(Norm[v1] Norm[v2]))^2;

D11[v1_,v2_]:=S2[v1,v2] (v1[[3]] v2[[3]]/(Norm[v1] Norm[v2]))^2;

D12[v1_,v2_]:=(-v1[[3]]-v2[[3]]) ((v1[[3]]/Norm[v1])^4 v2[[3]]/Norm[v2]^2+(v2[[3]]/Norm[v2])^4 v1[[3]]/Norm[v1]^2+2 (v2[[3]]/Norm[v2])^2 v1[[3]]^3/Norm[v1]^4+2 (v1[[3]]/Norm[v1])^2 v2[[3]]^3/Norm[v2]^4);

D13[v1_,v2_]:=((v1[[3]] v2[[3]] (-v1[[3]]-v2[[3]]))/(Norm[v1] Norm[v2] Sqrt[(-v1[[1]]-v2[[1]])^2+(-v1[[2]]-v2[[2]])^2+(-v1[[3]]-v2[[3]])^2]))^2 G2[v1,v2];

D14[v1_,v2_]:=(-v1[[3]]-v2[[3]]) (v1[[3]]^3 (v2[[3]]/(Norm[v1] Norm[v2]))^4+v2[[3]]^3 (v1[[3]]/(Norm[v1] Norm[v2]))^4);


Dlist={D1,D2,D3,D4,D5,D6,D7,D8,D9,D10,D11,D12,D13,D14};



End[] (*End Private Context*)

EndPackage[]



