(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)

BeginPackage["savefcts`"]

savefunc::usage=" save results";

Begin["`Private`"]
 savefunc[M0_]:=Module[{M=M0},
n=Length[M];
fileName="savefile.txt";
Export[fileName,""];
file=OpenAppend[fileName,PageWidth->Infinity];

For[i=1,i<n+1,i++,
datai=Total[M[[i]]]/. x_Integer:>N[x];
tosave="Sn"<>ToString[i]<>"="<>ToString[CForm[datai]]<>";";
Print[tosave];
WriteString[file,tosave,"\n"]
];
Close[file];
];
 
End[] (*End Private Context*)
 
EndPackage[]



