(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)

BeginPackage["savefcts`"]

savefunc::usage=" save results";

Begin["`Private`"]
Get[NotebookDirectory[]<>"globalvars.m"] ;
(*Save output in a format that's easy to use in C code*)

savefunc[SM0_,UnSM0_,Symdivergences0_,UnSymdivergences0_,biases0_]:=Module[{SM=SM0,UnSM=UnSM0,Symdivergences=Symdivergences0,UnSymdivergences=UnSymdivergences0,biases=biases0},
n=Length[SM];
fileName="savefile.txt";
Export[fileName,""];
file=OpenAppend[fileName,PageWidth->Infinity];

For[b=1,b<Length[biases]+1,b++,
tosave="nu"<>ToString[b]<>"="<>ToString[CForm[biases[[b]]]]<>";";
WriteString[file,tosave,"\n"];
];

saveMdata[dataname0_,datamatr0_]:=Module[{dataname=dataname0,datamatr=datamatr0},
For[i=1,i<n+1,i++,For[j=1,j<n+1,j++,
datai=datamatr[[i,j]]/. x_Integer:>N[x];
term=dataname<>ToString[i]<>","<>ToString[j]<>"]";

tosave=term<>"="<>ToString[CForm[datai]]<>";";
WriteString[file,tosave,"\n"]
];];
];
saveMdata["Sym",SM];
saveMdata["UnSym",UnSM];
saveMdata["SymDivs",Symdivergences];
saveMdata["UnSymDivs",UnSymdivergences];

Close[file];
];
 
End[] 
 
EndPackage[]



