(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)

BeginPackage["util`"]

Simplfunc::usage="Simplify an expression";

Begin["`Private`"]
Get[NotebookDirectory[]<>"globalvars.m"] ;
(*$Assumptions= k0>=0&&q0>=0&&kmq>=0&& 2 Pi>=phi>=0 && 1>=muk>=-1 && 1>=muq>=-1 && \[Epsilon] > 0&&{ k0,q0,muk, muq,phi, \[Epsilon],\[Nu]}\[Element]Reals;*)

 Simplfunc[expr0_]:=Module[{exprini=expr0},
(*Print[exprini];*)
expr=exprini/. {Norm[k]^2->k0^2,Norm[q]^2->q0^2,Norm[k-q]^2->kmq^2,Sqrt[1-muk^2] Sqrt[1-muq^2] Sin[phi]->(-kmq^2+k0^2+q0^2)/(2 k0 q0)-muk muq};
expr=Rationalize[Simplify[expr]]/. {Sin[phi]->(((-kmq^2+k0^2+q0^2)/(2 k0 q0))-muk muq)/(Sqrt[1-muk^2] Sqrt[1-muq^2])};
Expand[Simplify[expr]]
];
 
End[] (*End Private Context*)
 
EndPackage[]



